project:
  title: "MATH 3339: Introduction to Data Science with LLMs"
  type: website

website:
  site-url: https://paulsavala.github.io/math-3339-intro-data-science-with-llms/

format:
  html:
    css: styles/textbook-nav.css

execute:
  freeze: auto
