project:
  title: "MATH 3339: Introduction to Data Science"
  type: website

website:
  site-url: https://paulsavala.github.io/math-3339/

format:
  html:
    css: styles/textbook-nav.css

execute:
  freeze: auto
